---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  replicas: 2
  template:
    spec:
      initContainers:
        - name: copyutil
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 256Mi
      containers:
        - name: dex
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
