---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: haproxy-public
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: argocd
data:
  ssl-redirect: 'true'
  ssl-redirect-port: '443'
  ssl-certificate: ingress-nginx/haproxy-public-default-tls
  forwarded-for: 'true'
