---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - haproxy-public-ingressclass.yaml
  - haproxy-public-service.yaml
  - haproxy-public-deployment.yaml
  - clusterissuer-letsencrypt-public.yaml
  - haproxy-public-default-certificate.yaml
  - haproxy-configmap.yaml
