---
log_level: INFO
engines:
  exaflow:
    URL: http://exaflow-controller-service:5000
network:
  LINK: direct
  EXTERNAL_PROTOCOL: http
  PUBLIC_PROTOCOL: http
datacatalog:
  PROTOCOL: https
  HOST: datacatalogue.mip.ebrains.eu
keycloak:
  AUTHENTICATION: 1
  INTERNAL_AUTH: 0
  PROTOCOL: https
  URL: iam.ebrains.eu
  REALM: MIP
  SSL_REQUIRED: external
platform-ui:
  ingress:
    redirectRootTo: ''
    className: haproxy-public
