---
name: IaC Security Scanning

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checkov-scan:
    name: Scan IaC with Checkov
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: kubernetes,helm,kustomize
          output_format: sarif
          output_file_path: checkov-results.sarif
          # skip three specific rules that produce false positives
          # these rules fires on ArgoCD resource types
          # Checkov doesn't fully understand ArgoCD and flags them incorrectly
          # also skip it for real Kubernetes workload files and this is a security gap
          skip_check: CKV_K8S_35,CKV_K8S_8,CKV_K8S_9 
                    

      - name: Upload SARIF to GitHub Security tab
        if: always() && hashFiles('checkov-results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-results.sarif
          category: iac-scanning